apiVersion: v2
name: phpmyadmin
description: phpMyAdmin on the official Docker Hub image (Docker Official Images).
type: application
version: 1.0.0
appVersion: "5"
keywords:
  - phpmyadmin
  - mysql
  - database
home: https://hub.docker.com/_/phpmyadmin
sources:
  - https://hub.docker.com/_/phpmyadmin
maintainers:
  - name: NebuaCloud