apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-admin
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.site.adminPassword | b64enc | quote }}