replicaCount: 1

image:
  repository: phpmyadmin/phpmyadmin
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: nginx
  hostname: phpmyadmin.local
  path: /
  pathType: ImplementationSpecific

mysql:
  host: mysql
  port: 3306
  rootPasswordSecretName: mysql-secret
  rootPasswordSecretKey: root-password
