apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mariadb
      protocol: TCP
      name: mariadb
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}