apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "phpmyadmin.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "phpmyadmin.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "phpmyadmin.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "phpmyadmin.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: phpmyadmin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: PMA_HOST
              value: {{ .Values.mysql.host | quote }}
            - name: PMA_PORT
              value: {{ .Values.mysql.port | quote }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.rootPasswordSecretName | quote }}
                  key: {{ .Values.mysql.rootPasswordSecretKey | quote }}
