{{- if not .Values.externalDatabase.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odoo.dbSecretName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}