{{- if and .Values.registry (ne (default "" .Values.registry.token) "") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-registry-credentials" .Release.Name) .Values.registry.secretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "web-app.dockerconfigjson" . | b64enc }}
{{- end }}
